#get_filename_component(CDUMMY_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

#set(CDUMMY_INCLUDE_DIRS  "@CMAKE_INSTALL_FULL_INCLUDEDIR@")

# This is really stupid CONFIG_INSTALL_DIR = @CONFIG_INSTALL_DIR@
# This is really stupid CMAKE_INSTALL_FULL_INCLUDEDIR = @CMAKE_INSTALL_FULL_INCLUDEDIR@
@PACKAGE_INIT@
include("${CMAKE_CURRENT_LIST_DIR}/cdummy/CDummyTargets.cmake")